import { Inter } from "next/font/google";
import "@/app/dashboard/assets/css/bootstrap.min.css";
import "@/app/dashboard/assets/css/globals.css";
import "@/app/dashboard/assets/css/comman.css";
import "@/app/dashboard/assets/css/style.css";
import "@/app/dashboard/assets/css/responsive.css";
import { Providers } from "./Providers";
import HeadersTop from "@/app/dashboard/common/HeadersTop";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ paddingTop: 50 }} className={inter.className}>
        <Providers>
          <HeadersTop />
          {children}
        </Providers>
      </body>
    </html>
  );
}
